# Generated by Django 2.2.5 on 2019-10-23 23:02

import core.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('premier', '0001_initial'),
        ('sema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=20, unique=True)),
                ('premier_manufacturer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to='premier.PremierManufacturer')),
                ('sema_brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to='sema.SemaBrand', verbose_name='SEMA brand')),
            ],
            bases=(models.Model, core.mixins.MessagesMixin),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('premier_product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item', to='premier.PremierProduct')),
                ('sema_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='sema.SemaProduct', verbose_name='SEMA product')),
            ],
            bases=(models.Model, core.mixins.MessagesMixin),
        ),
    ]
