# Generated by Django 2.2.5 on 2019-10-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_item_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='slug',
            field=models.CharField(default='b', max_length=20),
            preserve_default=False,
        ),
    ]
