# Generated by Django 2.2.5 on 2019-10-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_vendor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='slug',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
