# Generated by Django 2.2.5 on 2019-10-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_item_is_relevant'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
