# Generated by Django 2.2.5 on 2019-11-05 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0004_shopify_null'),
        ('main', '0004_vendor_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='shopify_product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item', to='shopify.ShopifyProduct'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='shopify_vendor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to='shopify.ShopifyVendor'),
            preserve_default=False,
        ),
    ]
