# Generated by Django 2.2.5 on 2019-11-05 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_main_shopify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='shopify_vendor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to='shopify.ShopifyVendor'),
        ),
    ]
