# Generated by Django 2.2.5 on 2019-11-11 06:29

import core.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0015_shopifycollection_img'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0006_vendor_shopify_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grouping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_relevant', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'sema'), ('model', 'basevehicle')), models.Q(('app_label', 'sema'), ('model', 'vehicle')), models.Q(('app_label', 'sema'), ('model', 'category')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='content type')),
                ('shopify_collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grouping', to='shopify.ShopifyCollection')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, core.mixins.MessagesMixin),
        ),
    ]
