# Generated by Django 2.2.5 on 2019-11-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0015_shopifycollection_img'),
        ('main', '0008_grouping_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouping',
            name='shopify_collection',
        ),
        migrations.AddField(
            model_name='grouping',
            name='shopify_collections',
            field=models.ManyToManyField(related_name='grouping', to='shopify.ShopifyCollection'),
        ),
    ]
