# Generated by Django 2.2.5 on 2019-11-11 18:15

import core.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sema', '0048_semaengine_max_length'),
        ('shopify', '0015_shopifycollection_img'),
        ('main', '0009_grouping_shopify_collections'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_relevant', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('sema_branch_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_category_paths', to='sema.SemaCategory')),
                ('sema_leaf_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaf_category_paths', to='sema.SemaCategory')),
                ('sema_root_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='root_category_paths', to='sema.SemaCategory')),
                ('shopify_collections', models.ManyToManyField(related_name='category_paths', to='shopify.ShopifyCollection')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, core.mixins.MessagesMixin),
        ),
        migrations.DeleteModel(
            name='Grouping',
        ),
    ]
