# Generated by Django 2.2.5 on 2019-11-11 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sema', '0048_semaengine_max_length'),
        ('main', '0010_category_path'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categorypath',
            unique_together={('sema_root_category', 'sema_branch_category', 'sema_leaf_category')},
        ),
    ]
