# Generated by Django 2.2.5 on 2019-11-15 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0019_shopifycollection'),
        ('main', '0012_item_premier_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorypath',
            name='shopify_branch_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_category_paths', to='shopify.ShopifyCollection'),
        ),
        migrations.AddField(
            model_name='categorypath',
            name='shopify_leaf_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaf_category_paths', to='shopify.ShopifyCollection'),
        ),
        migrations.AddField(
            model_name='categorypath',
            name='shopify_root_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='root_category_paths', to='shopify.ShopifyCollection'),
        ),
    ]
