# Generated by Django 2.2.5 on 2019-11-15 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_categorypath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorypath',
            name='shopify_collections',
        ),
    ]
