# Generated by Django 2.2.5 on 2019-12-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorypath',
            name='relevancy_exceptions',
        ),
        migrations.RemoveField(
            model_name='item',
            name='relevancy_exceptions',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='relevancy_exceptions',
        ),
        migrations.AddField(
            model_name='categorypath',
            name='relevancy_exception',
            field=models.CharField(blank=True, max_length=255, verbose_name='exception'),
        ),
        migrations.AddField(
            model_name='item',
            name='relevancy_exception',
            field=models.CharField(blank=True, max_length=255, verbose_name='exception'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='relevancy_exception',
            field=models.CharField(blank=True, max_length=255, verbose_name='exception'),
        ),
    ]
