# Generated by Django 2.2.5 on 2019-11-05 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyCollectionRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.CharField(max_length=25)),
                ('relation', models.CharField(max_length=10)),
                ('condition', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ShopifyProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveIntegerField(blank=True, help_text='Populated by Shopify', null=True, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('body_html', models.TextField()),
                ('product_type', models.CharField(choices=[('Apparel', 'Apparel'), ('Automotive Parts', 'Automotive Parts')], default='Automotive Parts', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('published_scope', models.CharField(choices=[('web', 'web'), ('global', 'global')], default='web', max_length=10)),
                ('seo_title', models.CharField(blank=True, max_length=200)),
                ('seo_description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopifyTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopifyVendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopifyVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_id', models.PositiveIntegerField(blank=True, help_text='Populated by Shopify', null=True, unique=True)),
                ('image_id', models.PositiveIntegerField(blank=True, help_text='Populated by Shopify', null=True)),
                ('inventory_item_id', models.PositiveIntegerField(blank=True, help_text='Populated by Shopify', null=True)),
                ('title', models.CharField(max_length=30)),
                ('grams', models.PositiveIntegerField(blank=True, null=True)),
                ('weight', models.PositiveIntegerField(blank=True, null=True)),
                ('weight_unit', models.CharField(blank=True, choices=[('g', 'g'), ('kg', 'kg'), ('oz', 'oz'), ('lb', 'lb')], max_length=3, null=True)),
                ('inventory_management', models.CharField(choices=[('manual', 'manual'), ('create me', 'create me')], default='create me', max_length=100)),
                ('inventory_policy', models.CharField(choices=[('allow', 'allow'), ('deny', 'deny')], default='allow', max_length=10)),
                ('fulfillment_service', models.CharField(choices=[('manual', 'manual'), ('create me', 'create me')], default='manual', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sku', models.CharField(blank=True, max_length=50)),
                ('barcode', models.CharField(max_length=50)),
                ('is_taxable', models.BooleanField(default=True)),
                ('tax_code', models.CharField(max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shopify.ShopifyProduct')),
            ],
        ),
        migrations.AddField(
            model_name='shopifyproduct',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='shopify.ShopifyTag'),
        ),
        migrations.AddField(
            model_name='shopifyproduct',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shopify.ShopifyVendor'),
        ),
        migrations.CreateModel(
            name='ShopifyOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_id', models.PositiveIntegerField(blank=True, help_text='Populated by Shopify', null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='shopify.ShopifyProduct')),
            ],
        ),
        migrations.CreateModel(
            name='ShopifyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.PositiveIntegerField(blank=True, help_text='Populated by Shopify', null=True, unique=True)),
                ('src', models.URLField(max_length=250)),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shopify.ShopifyProduct')),
            ],
        ),
        migrations.CreateModel(
            name='ShopifyCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_id', models.PositiveIntegerField(blank=True, help_text='Populated by Shopify', null=True, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('body_html', models.TextField()),
                ('image_src', models.URLField(max_length=250)),
                ('image_alt', models.CharField(max_length=30)),
                ('is_published', models.BooleanField(default=False)),
                ('published_scope', models.CharField(choices=[('web', 'web'), ('global', 'global')], default='web', max_length=10)),
                ('disjunctive', models.BooleanField(default=False)),
                ('sort_order', models.CharField(choices=[('alpha-asc', 'Alphabetical (ascending)'), ('alpha-dec', 'Alphabetical (descending)'), ('created', 'Creation Date (ascending)'), ('created-desc', 'Creation Date (descending)'), ('price-asc', 'Price (ascending)'), ('price-desc', 'Price (descending)'), ('best-selling', 'Best Selling')], default='best-selling', max_length=15)),
                ('rules', models.ManyToManyField(blank=True, related_name='collections', to='shopify.ShopifyCollectionRule')),
                ('tags', models.ManyToManyField(blank=True, related_name='collections', to='shopify.ShopifyTag')),
            ],
        ),
    ]
