# Generated by Django 2.2.5 on 2019-11-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0002_shopify_relevancy_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifyvariant',
            name='title',
            field=models.CharField(default='Default Title', max_length=30),
        ),
    ]
