# Generated by Django 2.2.5 on 2019-11-05 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0003_shopifyvariant_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifyproduct',
            name='body_html',
            field=models.TextField(blank=True, verbose_name='body HTML'),
        ),
        migrations.AlterField(
            model_name='shopifyproduct',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='shopifyproduct',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shopify.ShopifyVendor'),
        ),
        migrations.AlterField(
            model_name='shopifyvariant',
            name='barcode',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='shopifyvariant',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='shopifyvariant',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='shopifyvariant',
            name='tax_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
