# Generated by Django 2.2.5 on 2019-11-06 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0004_shopify_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyCalculator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calculator', to='shopify.ShopifyProduct')),
            ],
        ),
    ]
