# Generated by Django 2.2.5 on 2019-11-06 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0005_shopifycalculator'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyMetafield',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metafield_id', models.PositiveIntegerField(blank=True, help_text='Populated by Shopify', null=True, unique=True)),
                ('owner_resource', models.CharField(choices=[('product', 'product')], default='product', max_length=10)),
                ('name_space', models.CharField(max_length=20)),
                ('value_type', models.CharField(choices=[('string', 'string'), ('integer', 'integer'), ('json', 'json')], default='string', max_length=10)),
                ('key', models.CharField(max_length=30)),
                ('value', models.TextField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metafields', to='shopify.ShopifyProduct')),
            ],
            options={
                'unique_together': {('product', 'name_space', 'key')},
            },
        ),
    ]
