# Generated by Django 2.2.5 on 2019-11-06 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0006_shopifymetafield'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopifyoption',
            old_name='value',
            new_name='values',
        ),
        migrations.AlterUniqueTogether(
            name='shopifymetafield',
            unique_together={('product', 'owner_resource', 'name_space', 'key')},
        ),
    ]
