# Generated by Django 2.2.5 on 2019-11-07 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0007_shopify'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopifymetafield',
            old_name='name_space',
            new_name='namespace',
        ),
        migrations.AlterField(
            model_name='shopifyvariant',
            name='inventory_management',
            field=models.CharField(choices=[('manual', 'manual'), ('create me', 'create me')], default='manual', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='shopifymetafield',
            unique_together={('product', 'owner_resource', 'namespace', 'key')},
        ),
    ]
