# Generated by Django 2.2.5 on 2019-11-07 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0008_shopify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifyproduct',
            name='published_scope',
            field=models.CharField(choices=[('web', 'web'), ('global', 'global')], default='global', max_length=10),
        ),
    ]
