# Generated by Django 2.2.5 on 2019-11-07 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0009_shopifyproduct_scope'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopifyimage',
            name='image_id',
        ),
        migrations.RemoveField(
            model_name='shopifyimage',
            name='position',
        ),
        migrations.RemoveField(
            model_name='shopifyvariant',
            name='image_id',
        ),
        migrations.RemoveField(
            model_name='shopifyvariant',
            name='inventory_item_id',
        ),
        migrations.AlterField(
            model_name='shopifycollection',
            name='collection_id',
            field=models.IntegerField(blank=True, help_text='Populated by Shopify', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='shopifymetafield',
            name='metafield_id',
            field=models.IntegerField(blank=True, help_text='Populated by Shopify', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='shopifyoption',
            name='option_id',
            field=models.IntegerField(blank=True, help_text='Populated by Shopify', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='shopifyproduct',
            name='product_id',
            field=models.IntegerField(blank=True, help_text='Populated by Shopify', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='shopifyvariant',
            name='grams',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shopifyvariant',
            name='variant_id',
            field=models.IntegerField(blank=True, help_text='Populated by Shopify', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='shopifyvariant',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
