# Generated by Django 2.2.5 on 2019-11-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0011_shopify_integer_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifyproduct',
            name='published_scope',
            field=models.CharField(choices=[('web', 'web'), ('global', 'global')], default='web', max_length=10),
        ),
        migrations.AlterField(
            model_name='shopifyvariant',
            name='fulfillment_service',
            field=models.CharField(blank=True, choices=[('manual', 'manual'), ('create me', 'create me')], max_length=100),
        ),
        migrations.AlterField(
            model_name='shopifyvariant',
            name='inventory_management',
            field=models.CharField(blank=True, choices=[('manual', 'manual'), ('create me', 'create me')], max_length=100),
        ),
        migrations.AlterField(
            model_name='shopifyvariant',
            name='inventory_policy',
            field=models.CharField(blank=True, choices=[('allow', 'allow'), ('deny', 'deny')], max_length=10),
        ),
        migrations.AlterField(
            model_name='shopifyvariant',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='shopifyvariant',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('g', 'g'), ('kg', 'kg'), ('oz', 'oz'), ('lb', 'lb')], default='', max_length=3),
            preserve_default=False,
        ),
    ]
