# Generated by Django 2.2.5 on 2019-11-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0012_shopify_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifyoption',
            name='name',
            field=models.CharField(default='Title', max_length=100),
        ),
        migrations.AlterField(
            model_name='shopifyoption',
            name='values',
            field=models.TextField(default="['Default Title']"),
        ),
    ]
