# Generated by Django 2.2.5 on 2019-11-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0014_shopifyoption_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifycollection',
            name='image_alt',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='shopifycollection',
            name='image_src',
            field=models.URLField(blank=True, max_length=250),
        ),
    ]
