# Generated by Django 2.2.5 on 2019-11-14 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('shopify', '0015_shopifycollection_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifymetafield',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'shopify'), ('model', 'shopifyproduct')), models.Q(('app_label', 'shopify'), ('model', 'shopifycollection')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='shopifymetafield',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shopifymetafield',
            name='owner_resource',
            field=models.CharField(choices=[('product', 'product'), ('collection', 'collection')], default='product', max_length=10),
        ),
    ]
