# Generated by Django 2.2.5 on 2019-11-14 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0017_shopifymetafield'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShopifyCalculator',
            new_name='ShopifyProductCalculator',
        ),
    ]
