# Generated by Django 2.2.5 on 2019-11-16 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0019_shopifycollection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifymetafield',
            name='owner_resource',
            field=models.CharField(choices=[('product', 'product'), ('smart_collection', 'collection')], default='product', max_length=10),
        ),
    ]
