# Generated by Django 2.2.5 on 2019-11-16 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0020_shopifymetafield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifymetafield',
            name='owner_resource',
            field=models.CharField(choices=[('product', 'product'), ('smart_collection', 'collection')], max_length=20),
        ),
    ]
