# Generated by Django 2.2.5 on 2019-11-26 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0022_shopifymetafield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopifycollection',
            name='is_relevant',
        ),
        migrations.RemoveField(
            model_name='shopifycollection',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='shopifyproduct',
            name='is_relevant',
        ),
        migrations.RemoveField(
            model_name='shopifyproduct',
            name='notes',
        ),
    ]
