# Generated by Django 2.2.5 on 2019-11-28 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0023_shopify_relevancy_and_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifycollectioncalculator',
            name='metafields_display_name_option',
            field=models.CharField(choices=[('sema_category_display_name_value', 'SEMA Category'), ('custom_value', 'Custom')], default='sema_category_display_name_value', max_length=50),
        ),
        migrations.AddField(
            model_name='shopifycollectioncalculator',
            name='metafields_subcollections_option',
            field=models.CharField(choices=[('shopify_subcollections_value', 'Shopify Subcollections'), ('custom_value', 'Custom')], default='shopify_subcollections_value', max_length=50),
        ),
        migrations.AddField(
            model_name='shopifycollectioncalculator',
            name='tags_categories_option',
            field=models.CharField(choices=[('sema_category_tags_value', 'SEMA Categories'), ('custom_value', 'Custom')], default='sema_category_tags_value', max_length=50),
        ),
        migrations.AddField(
            model_name='shopifycollectioncalculator',
            name='title_option',
            field=models.CharField(choices=[('sema_category_chained_title_value', 'SEMA Categories'), ('custom_value', 'Custom')], default='sema_category_chained_title_value', max_length=50),
        ),
        migrations.AddField(
            model_name='shopifyproductcalculator',
            name='body_html_option',
            field=models.CharField(choices=[('sema_description_def_value', 'SEMA Definition'), ('sema_description_des_value', 'SEMA Description'), ('sema_description_inv_value', 'SEMA Invoice'), ('sema_description_ext_value', 'SEMA Extended'), ('sema_description_tle_value', 'SEMA Title'), ('sema_description_sho_value', 'SEMA Short'), ('sema_description_asc_value', 'SEMA ASC'), ('sema_description_mkt_value', 'SEMA Marketing'), ('premier_description_value', 'Premier Description'), ('custom_value', 'Custom')], default='sema_description_ext_value', max_length=50),
        ),
        migrations.AddField(
            model_name='shopifyproductcalculator',
            name='images_option',
            field=models.CharField(choices=[('all_images_value', 'All Images'), ('sema_images_value', 'SEMA Images'), ('premier_images_value', 'Premier Images'), ('custom_value', 'Custom')], default='sema_images_value', max_length=50),
        ),
        migrations.AddField(
            model_name='shopifyproductcalculator',
            name='metafields_fitments_option',
            field=models.CharField(choices=[('sema_vehicle_fitments_value', 'SEMA Vehicles'), ('custom_value', 'Custom')], default='sema_vehicle_fitments_value', max_length=50),
        ),
        migrations.AddField(
            model_name='shopifyproductcalculator',
            name='metafields_packaging_option',
            field=models.CharField(choices=[('sema_html_packaging_value', 'SEMA HTML'), ('custom_value', 'Custom')], default='sema_html_packaging_value', max_length=50),
        ),
        migrations.AddField(
            model_name='shopifyproductcalculator',
            name='tags_categories_option',
            field=models.CharField(choices=[('sema_category_tags_value', 'SEMA Categories'), ('custom_value', 'Custom')], default='sema_category_tags_value', max_length=50),
        ),
        migrations.AddField(
            model_name='shopifyproductcalculator',
            name='tags_vendor_option',
            field=models.CharField(choices=[('sema_brand_tags_value', 'SEMA Brand'), ('custom_value', 'Custom')], default='sema_brand_tag_value', max_length=50),
        ),
        migrations.AddField(
            model_name='shopifyproductcalculator',
            name='title_option',
            field=models.CharField(choices=[('sema_description_def_value', 'SEMA Definition'), ('sema_description_des_value', 'SEMA Description'), ('sema_description_inv_value', 'SEMA Invoice'), ('sema_description_ext_value', 'SEMA Extended'), ('sema_description_tle_value', 'SEMA Title'), ('sema_description_sho_value', 'SEMA Short'), ('sema_description_asc_value', 'SEMA ASC'), ('sema_description_mkt_value', 'SEMA Marketing'), ('premier_description_value', 'Premier Description'), ('custom_value', 'Custom')], default='sema_description_sho_value', max_length=50),
        ),
        migrations.AddField(
            model_name='shopifyproductcalculator',
            name='variant_barcode_option',
            field=models.CharField(choices=[('premier_upc_value', 'Premier UPC'), ('custom_value', 'Custom')], default='premier_upc_value', max_length=50),
        ),
        migrations.AddField(
            model_name='shopifyproductcalculator',
            name='variant_cost_option',
            field=models.CharField(choices=[('premier_cost_cad_value', 'Premier Cost CAD'), ('premier_cost_usd_value', 'Premier Cost USD'), ('custom_value', 'Custom')], default='premier_cost_cad_value', max_length=50),
        ),
        migrations.AddField(
            model_name='shopifyproductcalculator',
            name='variant_price_base_option',
            field=models.CharField(choices=[('premier_cost_cad_value', 'Premier Cost CAD'), ('premier_cost_usd_value', 'Premier Cost USD'), ('custom_value', 'Custom')], default='premier_cost_cad_value', max_length=50),
        ),
        migrations.AddField(
            model_name='shopifyproductcalculator',
            name='variant_price_markup_option',
            field=models.CharField(choices=[('0.00', '0%'), ('0.05', '5%'), ('0.10', '10%'), ('0.15', '15%'), ('0.20', '20%'), ('0.25', '25%'), ('0.30', '30%'), ('0.35', '35%'), ('0.40', '40%')], default='0.20', max_length=5),
        ),
        migrations.AddField(
            model_name='shopifyproductcalculator',
            name='variant_sku_option',
            field=models.CharField(choices=[('premier_premier_part_number_value', 'Premier Part Number'), ('custom_value', 'Custom')], default='premier_premier_part_number_value', max_length=50),
        ),
        migrations.AddField(
            model_name='shopifyproductcalculator',
            name='variant_weight_option',
            field=models.CharField(choices=[('premier_weight_value', 'Premier Weight'), ('custom_value', 'Custom')], default='premier_weight_value', max_length=50),
        ),
        migrations.AddField(
            model_name='shopifyproductcalculator',
            name='variant_weight_unit_option',
            field=models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('oz', 'oz'), ('lb', 'lb')], default='lb', max_length=5),
        ),
    ]
