# Generated by Django 2.2.5 on 2019-11-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0024_shopify_calculators'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifyimage',
            name='image_id',
            field=models.BigIntegerField(blank=True, help_text='Populated by Shopify', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='shopifyproductcalculator',
            name='tags_vendor_option',
            field=models.CharField(choices=[('sema_brand_tags_value', 'SEMA Brand'), ('custom_value', 'Custom')], default='sema_brand_tags_value', max_length=50),
        ),
    ]
