# Generated by Django 2.2.5 on 2019-11-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0025_shopifyimage_image_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifyimage',
            name='link',
            field=models.URLField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='shopifyimage',
            name='src',
            field=models.URLField(blank=True, help_text='Populated by Shopify', max_length=250),
        ),
    ]
