# Generated by Django 2.2.5 on 2019-11-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0026_shopifyimage_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifyimage',
            name='link',
            field=models.URLField(max_length=250),
        ),
    ]
