# Generated by Django 2.2.5 on 2019-11-29 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0027_shopifyimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifycollectionrule',
            name='condition',
            field=models.CharField(max_length=200),
        ),
    ]
