# Generated by Django 2.2.5 on 2019-12-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0030_shopifyproductcalculator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifyproductcalculator',
            name='title_choice',
            field=models.CharField(choices=[('sema_description_def_value', 'SEMA DEF Description'), ('sema_description_des_value', 'SEMA DES Description'), ('sema_description_inv_value', 'SEMA INV Description'), ('sema_description_ext_value', 'SEMA EXT Description'), ('sema_description_tle_value', 'SEMA TLE Description'), ('sema_description_sho_value', 'SEMA SHO Description'), ('sema_description_mkt_value', 'SEMA MKT Description'), ('sema_description_key_value', 'SEMA KEY Description'), ('sema_description_asc_value', 'SEMA ASC Description'), ('sema_description_asm_value', 'SEMA ASM Description'), ('sema_description_fab_value', 'SEMA FAB Description'), ('sema_description_lab_value', 'SEMA LAB Description'), ('sema_description_shp_value', 'SEMA SHP Description'), ('sema_description_oth_value', 'SEMA OTH Description'), ('premier_description_value', 'Premier Description'), ('custom_title_value', 'Custom Title')], default='sema_description_sho_value', max_length=50),
        ),
    ]
