# Generated by Django 2.2.5 on 2019-12-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0032_shopifyproductcalculator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopifycollectioncalculator',
            name='metafields_display_name_option',
        ),
        migrations.RemoveField(
            model_name='shopifycollectioncalculator',
            name='metafields_subcollections_option',
        ),
        migrations.RemoveField(
            model_name='shopifycollectioncalculator',
            name='tags_categories_option',
        ),
        migrations.RemoveField(
            model_name='shopifycollectioncalculator',
            name='title_option',
        ),
        migrations.AddField(
            model_name='shopifycollectioncalculator',
            name='metafield_value_collection_family_choice',
            field=models.CharField(choices=[('shopify_collection_collection_family_value', 'Shopify Collection Family'), ('custom_collection_family_metafield_value_value', 'Custom Collection Family Metafield Value')], default='shopify_collection_family_value', max_length=50),
        ),
        migrations.AddField(
            model_name='shopifycollectioncalculator',
            name='metafield_value_collection_family_custom_value',
            field=models.TextField(blank=True, help_text='format: {"grandparent_collection", "parent_collection", "child_collections"}'),
        ),
        migrations.AddField(
            model_name='shopifycollectioncalculator',
            name='metafield_value_display_name_choice',
            field=models.CharField(choices=[('sema_category_title_value', 'SEMA Category Title'), ('custom_display_name_metafield_value_value', 'Custom Display Name Metafield Value')], default='sema_category_title_value', max_length=50),
        ),
        migrations.AddField(
            model_name='shopifycollectioncalculator',
            name='metafield_value_display_name_custom_value',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='shopifycollectioncalculator',
            name='metafields_choice',
            field=models.CharField(choices=[('metafields_dict_all_value', 'All Metafields'), ('metafields_dict_display_name_value', 'Display Name Metafields'), ('metafields_dict_collection_family_value', 'Collection Family Metafields'), ('metafields_dict_custom_value', 'Custom Metafields')], default='metafields_dict_all_value', max_length=50),
        ),
        migrations.AddField(
            model_name='shopifycollectioncalculator',
            name='metafields_custom_value',
            field=models.TextField(blank=True, help_text='format: [{"namespace", "key", "owner_resource", "value", "value_type"}]'),
        ),
        migrations.AddField(
            model_name='shopifycollectioncalculator',
            name='tag_names_collection_choice',
            field=models.CharField(choices=[('sema_category_tag_names_value', 'SEMA Category Tag Names'), ('custom_collection_tag_names_value', 'Custom Collection Tag Names')], default='sema_category_tag_names_value', max_length=50),
        ),
        migrations.AddField(
            model_name='shopifycollectioncalculator',
            name='tag_names_collection_custom_value',
            field=models.TextField(blank=True, help_text='format: [""]'),
        ),
        migrations.AddField(
            model_name='shopifycollectioncalculator',
            name='tags_choice',
            field=models.CharField(choices=[('tags_dict_all_value', 'All Tags'), ('tags_dict_collection_value', 'Collection Tags'), ('tags_dict_custom_value', 'Custom Tags')], default='tags_dict_all_value', max_length=50),
        ),
        migrations.AddField(
            model_name='shopifycollectioncalculator',
            name='tags_custom_value',
            field=models.TextField(blank=True, help_text='format: [{"name"}]'),
        ),
        migrations.AddField(
            model_name='shopifycollectioncalculator',
            name='title_choice',
            field=models.CharField(choices=[('sema_category_chained_title_value', 'SEMA Category Chained Title'), ('custom_title_value', 'Custom Title')], default='sema_category_chained_title_value', max_length=50),
        ),
        migrations.AddField(
            model_name='shopifycollectioncalculator',
            name='title_custom_value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='shopifyproductcalculator',
            name='metafields_custom_value',
            field=models.TextField(blank=True, help_text='format: [{"namespace", "key", "owner_resource", "value", "value_type"}]'),
        ),
    ]
