# Generated by Django 2.2.5 on 2019-10-23 23:02

import core.mixins
from django.db import migrations, models
import django.db.models.deletion
import premier.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PremierManufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('primary_image', models.ImageField(blank=True, null=True, upload_to=premier.utils.premier_manufacturer_image_path)),
            ],
            bases=(models.Model, core.mixins.MessagesMixin),
        ),
        migrations.CreateModel(
            name='PremierProduct',
            fields=[
                ('inventory_ab', models.IntegerField(blank=True, help_text='API field', null=True, verbose_name='Alberta inventory')),
                ('inventory_po', models.IntegerField(blank=True, help_text='API field', null=True, verbose_name='PO inventory')),
                ('inventory_ut', models.IntegerField(blank=True, help_text='API field', null=True, verbose_name='Utah inventory')),
                ('inventory_ky', models.IntegerField(blank=True, help_text='API field', null=True, verbose_name='Kentucky inventory')),
                ('inventory_tx', models.IntegerField(blank=True, help_text='API field', null=True, verbose_name='Texas inventory')),
                ('inventory_ca', models.IntegerField(blank=True, help_text='API field', null=True, verbose_name='California inventory')),
                ('inventory_wa', models.IntegerField(blank=True, help_text='API field', null=True, verbose_name='Washington inventory')),
                ('inventory_co', models.IntegerField(blank=True, help_text='API field', null=True, verbose_name='Colorado inventory')),
                ('cost_cad', models.DecimalField(blank=True, decimal_places=2, help_text='API field', max_digits=10, null=True, verbose_name='cost CAD')),
                ('cost_usd', models.DecimalField(blank=True, decimal_places=2, help_text='API field', max_digits=10, null=True, verbose_name='cost USD')),
                ('jobber_cad', models.DecimalField(blank=True, decimal_places=2, help_text='API field', max_digits=10, null=True, verbose_name='jobber CAD')),
                ('jobber_usd', models.DecimalField(blank=True, decimal_places=2, help_text='API field', max_digits=10, null=True, verbose_name='jobber USD')),
                ('msrp_cad', models.DecimalField(blank=True, decimal_places=2, help_text='API field', max_digits=10, null=True, verbose_name='MSRP CAD')),
                ('msrp_usd', models.DecimalField(blank=True, decimal_places=2, help_text='API field', max_digits=10, null=True, verbose_name='MSRP USD')),
                ('map_cad', models.DecimalField(blank=True, decimal_places=2, help_text='API field', max_digits=10, null=True, verbose_name='MAP CAD')),
                ('map_usd', models.DecimalField(blank=True, decimal_places=2, help_text='API field', max_digits=10, null=True, verbose_name='MAP USD')),
                ('premier_part_number', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('vendor_part_number', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jobber', models.DecimalField(decimal_places=2, max_digits=10)),
                ('msrp', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='MSRP')),
                ('map', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='MAP')),
                ('part_status', models.CharField(max_length=20)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='lbs', max_digits=10, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, help_text='in', max_digits=10, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, help_text='in', max_digits=10, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='in', max_digits=10, null=True)),
                ('upc', models.CharField(blank=True, max_length=50, verbose_name='UPC')),
                ('primary_image', models.ImageField(blank=True, null=True, upload_to=premier.utils.premier_product_image_path)),
                ('is_relevant', models.BooleanField(default=False)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='premier.PremierManufacturer')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, core.mixins.MessagesMixin),
        ),
    ]
