# Generated by Django 2.2.5 on 2019-10-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='premierproduct',
            name='primary_image',
            field=models.ImageField(blank=True, null=True, upload_to='premier/product/images/'),
        ),
    ]
