# Generated by Django 2.2.5 on 2019-10-23 08:14

from django.db import migrations, models
import premier.utils


class Migration(migrations.Migration):

    dependencies = [
        ('premier', '0002_premierproduct_primary_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premierproduct',
            name='primary_image',
            field=models.ImageField(blank=True, null=True, upload_to=premier.utils.premier_product_image_path),
        ),
    ]
