# Generated by Django 2.2.5 on 2019-10-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premier', '0002_premierproduct_premier_part_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premierproduct',
            name='vendor_part_number',
            field=models.CharField(max_length=30),
        ),
    ]
