# Generated by Django 2.2.5 on 2019-10-24 23:05

from django.db import migrations, models
import premier.utils


class Migration(migrations.Migration):

    dependencies = [
        ('premier', '0004_premiermanufacturer_is_relevant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premierproduct',
            name='primary_image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=premier.utils.premier_product_image_path),
        ),
    ]
