# Generated by Django 2.2.5 on 2019-10-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premier', '0005_premierproduct_primary_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiermanufacturer',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
