# Generated by Django 2.2.5 on 2019-11-26 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premier', '0007_premierproduct_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premiermanufacturer',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='premierproduct',
            name='notes',
        ),
    ]
