# Generated by Django 2.2.5 on 2019-12-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premier', '0009_premiermanufacturer_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiermanufacturer',
            name='slug',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
