# Generated by Django 2.2.5 on 2019-12-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premier', '0010_premiermanufacturer_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiermanufacturer',
            name='relevancy_exception',
            field=models.CharField(blank=True, max_length=255, verbose_name='exception'),
        ),
        migrations.AddField(
            model_name='premierproduct',
            name='relevancy_exception',
            field=models.CharField(blank=True, max_length=255, verbose_name='exception'),
        ),
    ]
