# Generated by Django 2.2.5 on 2019-09-25 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PremierProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premier_part_number', models.CharField(max_length=20, unique=True)),
                ('vendor_part_number', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=300)),
                ('msrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('map', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jobber', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('part_status', models.CharField(max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, help_text='lbs', max_digits=10)),
                ('length', models.DecimalField(decimal_places=2, help_text='in', max_digits=10)),
                ('width', models.DecimalField(decimal_places=2, help_text='in', max_digits=10)),
                ('height', models.DecimalField(decimal_places=2, help_text='in', max_digits=10)),
                ('upc', models.CharField(max_length=50)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Manufacturer')),
            ],
        ),
    ]
