# Generated by Django 2.2.5 on 2019-09-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premierproduct',
            name='manufacturer',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='Manufacturer',
        ),
    ]
