# Generated by Django 2.2.5 on 2019-09-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_add_product_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premierproduct',
            name='upc',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
