# Generated by Django 2.2.5 on 2019-09-25 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_update_product_upc_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premierproduct',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='premier_product', to='product.Product'),
        ),
    ]
