# Generated by Django 2.2.5 on 2019-09-27 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_add_sema_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premierproduct',
            name='id',
        ),
        migrations.RemoveField(
            model_name='premierproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='semabrand',
            name='id',
        ),
        migrations.RemoveField(
            model_name='semadataset',
            name='id',
        ),
        migrations.RemoveField(
            model_name='semaproduct',
            name='id',
        ),
        migrations.RemoveField(
            model_name='semaproduct',
            name='product',
        ),
        migrations.AddField(
            model_name='semaproduct',
            name='product_id',
            field=models.CharField(default=9, max_length=30, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='premierproduct',
            name='premier_part_number',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='semabrand',
            name='brand_id',
            field=models.CharField(default=9, max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='semabrand',
            name='name',
            field=models.CharField(default=9, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='semadataset',
            name='brand',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='sema_datasets', to='product.SemaBrand'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='semadataset',
            name='dataset_id',
            field=models.CharField(default=9, max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='semadataset',
            name='name',
            field=models.CharField(default=9, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='semaproduct',
            name='dataset',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='sema_products', to='product.SemaDataset'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
