# Generated by Django 2.2.5 on 2019-09-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_add_primary_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premierproduct',
            name='vendor_part_number',
            field=models.CharField(max_length=20),
        ),
    ]
