# Generated by Django 2.2.5 on 2019-09-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_vendor_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premierproduct',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='in', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='premierproduct',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='in', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='premierproduct',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='lbs', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='premierproduct',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='in', max_digits=10, null=True),
        ),
    ]
