# Generated by Django 2.2.5 on 2019-09-27 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_dimension_null_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='premierproduct',
            name='cost_cad',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='API field', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='premierproduct',
            name='cost_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='API field', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='premierproduct',
            name='jobber_cad',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='API field', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='premierproduct',
            name='jobber_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='API field', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='premierproduct',
            name='map_cad',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='API field', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='premierproduct',
            name='map_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='API field', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='premierproduct',
            name='msrp_cad',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='API field', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='premierproduct',
            name='msrp_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='API field', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='premierproduct',
            name='inventory_ab',
            field=models.IntegerField(blank=True, help_text='API field', null=True, verbose_name='Alberta inventory'),
        ),
        migrations.AlterField(
            model_name='premierproduct',
            name='inventory_ca',
            field=models.IntegerField(blank=True, help_text='API field', null=True, verbose_name='California inventory'),
        ),
        migrations.AlterField(
            model_name='premierproduct',
            name='inventory_co',
            field=models.IntegerField(blank=True, help_text='API field', null=True, verbose_name='Colorado inventory'),
        ),
        migrations.AlterField(
            model_name='premierproduct',
            name='inventory_ky',
            field=models.IntegerField(blank=True, help_text='API field', null=True, verbose_name='Kentucky inventory'),
        ),
        migrations.AlterField(
            model_name='premierproduct',
            name='inventory_po',
            field=models.IntegerField(blank=True, help_text='API field', null=True, verbose_name='PO inventory'),
        ),
        migrations.AlterField(
            model_name='premierproduct',
            name='inventory_tx',
            field=models.IntegerField(blank=True, help_text='API field', null=True, verbose_name='Texas inventory'),
        ),
        migrations.AlterField(
            model_name='premierproduct',
            name='inventory_ut',
            field=models.IntegerField(blank=True, help_text='API field', null=True, verbose_name='Utah inventory'),
        ),
        migrations.AlterField(
            model_name='premierproduct',
            name='inventory_wa',
            field=models.IntegerField(blank=True, help_text='API field', null=True, verbose_name='Washington inventory'),
        ),
    ]
