# Generated by Django 2.2.5 on 2019-09-27 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_add_premier_api_price_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premierproduct',
            name='cost_cad',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='API field', max_digits=10, null=True, verbose_name='cost CAD'),
        ),
        migrations.AlterField(
            model_name='premierproduct',
            name='cost_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='API field', max_digits=10, null=True, verbose_name='cost USD'),
        ),
        migrations.AlterField(
            model_name='premierproduct',
            name='jobber_cad',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='API field', max_digits=10, null=True, verbose_name='jobber CAD'),
        ),
        migrations.AlterField(
            model_name='premierproduct',
            name='jobber_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='API field', max_digits=10, null=True, verbose_name='jobber USD'),
        ),
        migrations.AlterField(
            model_name='premierproduct',
            name='map',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='MAP'),
        ),
        migrations.AlterField(
            model_name='premierproduct',
            name='map_cad',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='API field', max_digits=10, null=True, verbose_name='MAP CAD'),
        ),
        migrations.AlterField(
            model_name='premierproduct',
            name='map_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='API field', max_digits=10, null=True, verbose_name='MAP USD'),
        ),
        migrations.AlterField(
            model_name='premierproduct',
            name='msrp',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='MSRP'),
        ),
        migrations.AlterField(
            model_name='premierproduct',
            name='msrp_cad',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='API field', max_digits=10, null=True, verbose_name='MSRP CAD'),
        ),
        migrations.AlterField(
            model_name='premierproduct',
            name='msrp_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='API field', max_digits=10, null=True, verbose_name='MSRP USD'),
        ),
        migrations.AlterField(
            model_name='premierproduct',
            name='upc',
            field=models.CharField(blank=True, max_length=50, verbose_name='UPC'),
        ),
    ]
