# Generated by Django 2.2.5 on 2019-09-28 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_add_verbose_names'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semabrand',
            options={'verbose_name': 'SEMA brand'},
        ),
        migrations.AlterModelOptions(
            name='semadataset',
            options={'verbose_name': 'SEMA dataset'},
        ),
        migrations.AlterModelOptions(
            name='semaproduct',
            options={'verbose_name': 'SEMA product'},
        ),
    ]
