# Generated by Django 2.2.5 on 2019-09-28 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_add_verbose_names_to_sema_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='semadataset',
            name='is_authorized',
            field=models.BooleanField(default=False, help_text='brand has given access to dataset'),
        ),
    ]
