# Generated by Django 2.2.5 on 2019-09-28 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_semadataset_is_authorized'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemaBaseVehicle',
            fields=[
                ('base_vehicle_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'SEMA base vehicle',
            },
        ),
        migrations.CreateModel(
            name='SemaMake',
            fields=[
                ('make_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'SEMA make',
            },
        ),
        migrations.CreateModel(
            name='SemaModel',
            fields=[
                ('model_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('base_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.SemaBaseVehicle')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.SemaMake')),
            ],
            options={
                'verbose_name': 'SEMA model',
            },
        ),
        migrations.CreateModel(
            name='SemaVehicle',
            fields=[
                ('vehicle_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'SEMA vehicle',
            },
        ),
        migrations.CreateModel(
            name='SemaYear',
            fields=[
                ('year', models.PositiveSmallIntegerField(primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'SEMA year',
            },
        ),
        migrations.CreateModel(
            name='SemaSubmodel',
            fields=[
                ('submodel_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.SemaModel')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.SemaVehicle')),
            ],
            options={
                'verbose_name': 'SEMA submodel',
            },
        ),
    ]
