# Generated by Django 2.2.5 on 2019-09-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_semadataset_years'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semamodel',
            name='base_vehicle',
        ),
        migrations.RemoveField(
            model_name='semasubmodel',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='semamodel',
            name='base_vehicle_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semasubmodel',
            name='vehicle_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SemaBaseVehicle',
        ),
        migrations.DeleteModel(
            name='SemaVehicle',
        ),
    ]
