# Generated by Django 2.2.5 on 2019-09-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_fix_db_restrictions'),
    ]

    operations = [
        migrations.AddField(
            model_name='semaproduct',
            name='part_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
