# Generated by Django 2.2.5 on 2019-09-29 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premier_manufacturer', models.CharField(max_length=50, unique=True)),
                ('sema_brand', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
