# Generated by Django 2.2.5 on 2019-09-29 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='sema_brand',
            field=models.CharField(max_length=50, unique=True, verbose_name='SEMA brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sema_product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='product.SemaProduct', verbose_name='SEMA product'),
        ),
    ]
