# Generated by Django 2.2.5 on 2019-10-02 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_verbose_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sema_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='product.SemaProduct', verbose_name='SEMA product'),
        ),
    ]
