# Generated by Django 2.2.5 on 2019-10-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_fix_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='semaproduct',
            name='html',
            field=models.TextField(blank=True, verbose_name='HTML'),
        ),
    ]
