# Generated by Django 2.2.5 on 2019-10-08 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_add_related_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semamodel',
            name='base_vehicle_id',
        ),
    ]
