# Generated by Django 2.2.5 on 2019-10-08 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_remove_semamodel_base_vehicle_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semamodel',
            name='make',
        ),
    ]
