# Generated by Django 2.2.5 on 2019-10-08 23:09

from django.db import migrations, models
import django.db.models.deletion
import product.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_remove_submodel_relations'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemaBaseVehicle',
            fields=[
                ('base_vehicle_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_vehicles', to='product.SemaMake')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_vehicles', to='product.SemaModel')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_vehicles', to='product.SemaYear')),
            ],
            options={
                'verbose_name': 'SEMA base vehicle',
            },
            bases=(models.Model, product.mixins.SemaBaseVehicleMixin),
        ),
    ]
