# Generated by Django 2.2.5 on 2019-10-11 02:56

from django.db import migrations, models
import django.db.models.deletion
import product.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_semabasevehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemaVehicle',
            fields=[
                ('vehicle_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('base_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='product.SemaBaseVehicle')),
                ('submodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='product.SemaSubmodel')),
            ],
            options={
                'verbose_name': 'SEMA vehicle',
            },
            bases=(models.Model,),
        ),
    ]
