# Generated by Django 2.2.5 on 2019-10-11 04:17

from django.db import migrations, models
import django.db.models.deletion
import product.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_semavehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemaCategory',
            fields=[
                ('category_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_categories', to='product.SemaCategory')),
            ],
            options={
                'verbose_name': 'SEMA categories',
            },
            bases=(models.Model, product.mixins.SemaCategoryMixin),
        ),
    ]
