# Generated by Django 2.2.5 on 2019-10-12 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_semacategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semacategory',
            options={'verbose_name': 'SEMA category', 'verbose_name_plural': 'SEMA categories'},
        ),
    ]
