# Generated by Django 2.2.5 on 2019-10-12 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_semayear_is_authorized'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semayear',
            options={'ordering': ['year'], 'verbose_name': 'SEMA year'},
        ),
    ]
