# Generated by Django 2.2.5 on 2019-10-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_seamyear_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semabasevehicle',
            options={'ordering': ['make', 'model', 'year'], 'verbose_name': 'SEMA base vehicle'},
        ),
        migrations.AlterModelOptions(
            name='semabrand',
            options={'ordering': ['name'], 'verbose_name': 'SEMA brand'},
        ),
        migrations.AlterModelOptions(
            name='semacategory',
            options={'ordering': ['name'], 'verbose_name': 'SEMA category', 'verbose_name_plural': 'SEMA categories'},
        ),
        migrations.AlterModelOptions(
            name='semadataset',
            options={'ordering': ['name'], 'verbose_name': 'SEMA dataset'},
        ),
        migrations.AlterModelOptions(
            name='semamake',
            options={'ordering': ['name'], 'verbose_name': 'SEMA make'},
        ),
        migrations.AlterModelOptions(
            name='semamodel',
            options={'ordering': ['name'], 'verbose_name': 'SEMA model'},
        ),
        migrations.AlterModelOptions(
            name='semaproduct',
            options={'ordering': ['dataset', 'part_number'], 'verbose_name': 'SEMA product'},
        ),
        migrations.AlterModelOptions(
            name='semasubmodel',
            options={'ordering': ['name'], 'verbose_name': 'SEMA submodel'},
        ),
        migrations.AlterModelOptions(
            name='semavehicle',
            options={'ordering': ['base_vehicle', 'submodel'], 'verbose_name': 'SEMA vehicle'},
        ),
        migrations.AddField(
            model_name='semabasevehicle',
            name='is_authorized',
            field=models.BooleanField(default=False, help_text='brand has given access to dataset'),
        ),
        migrations.AddField(
            model_name='semabrand',
            name='is_authorized',
            field=models.BooleanField(default=False, help_text='brand has given access to dataset'),
        ),
        migrations.AddField(
            model_name='semacategory',
            name='is_authorized',
            field=models.BooleanField(default=False, help_text='brand has given access to dataset'),
        ),
        migrations.AddField(
            model_name='semamake',
            name='is_authorized',
            field=models.BooleanField(default=False, help_text='brand has given access to dataset'),
        ),
        migrations.AddField(
            model_name='semamodel',
            name='is_authorized',
            field=models.BooleanField(default=False, help_text='brand has given access to dataset'),
        ),
        migrations.AddField(
            model_name='semaproduct',
            name='is_authorized',
            field=models.BooleanField(default=False, help_text='brand has given access to dataset'),
        ),
        migrations.AddField(
            model_name='semasubmodel',
            name='is_authorized',
            field=models.BooleanField(default=False, help_text='brand has given access to dataset'),
        ),
        migrations.AddField(
            model_name='semavehicle',
            name='is_authorized',
            field=models.BooleanField(default=False, help_text='brand has given access to dataset'),
        ),
    ]
