# Generated by Django 2.2.5 on 2019-10-14 12:11

from django.db import migrations, models
import django.db.models.deletion
import product.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_sema_authorized'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemaMakeYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_authorized', models.BooleanField(default=False, help_text='brand has given access to dataset')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='make_years', to='product.SemaMake')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='make_years', to='product.SemaYear')),
            ],
            options={
                'verbose_name': 'SEMA make year',
                'ordering': ['make', 'year'],
            },
            bases=(models.Model, product.mixins.MessagesMixin),
        ),
    ]
