# Generated by Django 2.2.5 on 2019-10-14 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_semamakeyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='semabasevehicle',
            name='make_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_vehicles', to='product.SemaMakeYear'),
        ),
    ]
