# Generated by Django 2.2.5 on 2019-10-14 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0038_semabasevehicle_make_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semabasevehicle',
            options={'ordering': ['make_year', 'model'], 'verbose_name': 'SEMA base vehicle'},
        ),
        migrations.RemoveField(
            model_name='semabasevehicle',
            name='make',
        ),
        migrations.RemoveField(
            model_name='semabasevehicle',
            name='year',
        ),
        migrations.AlterField(
            model_name='semabasevehicle',
            name='make_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_vehicles', to='product.SemaMakeYear'),
        ),
    ]
