# Generated by Django 2.2.5 on 2019-10-14 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0039_semabasevehicle_make_year'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='semamakeyear',
            unique_together={('make', 'year')},
        ),
    ]
