# Generated by Django 2.2.5 on 2019-10-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0040_makeyear_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semacategory',
            name='parent_category',
        ),
        migrations.AddField(
            model_name='semacategory',
            name='parent_categories',
            field=models.ManyToManyField(blank=True, related_name='_semacategory_parent_categories_+', to='product.SemaCategory'),
        ),
    ]
