# Generated by Django 2.2.5 on 2019-10-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0041_semacategory_parentcategories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semacategory',
            name='parent_categories',
            field=models.ManyToManyField(blank=True, related_name='child_categories', to='product.SemaCategory'),
        ),
    ]
