# Generated by Django 2.2.5 on 2019-10-20 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0042_semacategory_symetrical'),
    ]

    operations = [
        migrations.AddField(
            model_name='semaproduct',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='categories', to='product.SemaCategory'),
        ),
    ]
