# Generated by Django 2.2.5 on 2019-10-21 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0043_semaproduct_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='semaproduct',
            name='vehicles',
            field=models.ManyToManyField(blank=True, related_name='categories', to='product.SemaVehicle'),
        ),
    ]
