# Generated by Django 2.2.5 on 2019-10-21 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0044_semaproduct_vehicles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semaproduct',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='product.SemaCategory'),
        ),
        migrations.AlterField(
            model_name='semaproduct',
            name='vehicles',
            field=models.ManyToManyField(blank=True, related_name='products', to='product.SemaVehicle'),
        ),
    ]
