# Generated by Django 2.2.5 on 2019-10-21 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0045_semaproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semadataset',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='product.SemaBrand'),
        ),
        migrations.AlterField(
            model_name='semaproduct',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.SemaDataset'),
        ),
    ]
