# Generated by Django 2.2.5 on 2019-10-22 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0046_sema_related_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semaproduct',
            options={'ordering': ['dataset', 'part_number'], 'permissions': (('can_change_semaproduct_is_relevant', 'Can change SEMA product relevancy'),), 'verbose_name': 'SEMA product'},
        ),
        migrations.AddField(
            model_name='semaproduct',
            name='is_relevant',
            field=models.BooleanField(default=False),
        ),
    ]
