# Generated by Django 2.2.5 on 2019-10-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0047_semaproduct_relevant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semaproduct',
            options={'ordering': ['dataset', 'part_number'], 'verbose_name': 'SEMA product'},
        ),
        migrations.AddField(
            model_name='semavehicle',
            name='is_relevant',
            field=models.BooleanField(default=False),
        ),
    ]
