# Generated by Django 2.2.5 on 2019-10-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0048_semavehicle_relevant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semaproduct',
            name='is_relevant',
        ),
        migrations.AddField(
            model_name='premierproduct',
            name='is_relevant',
            field=models.BooleanField(default=False),
        ),
    ]
