# Generated by Django 2.2.5 on 2019-10-22 18:57

from django.db import migrations, models
import django.db.models.deletion
import product.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0049_premierproduct_relevant'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremierManufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            bases=(models.Model, product.mixins.MessagesMixin),
        ),
        migrations.AddField(
            model_name='premierproduct',
            name='manufacturer2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.PremierManufacturer'),
        ),
    ]
