# Generated by Django 2.2.5 on 2019-10-22 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0052_premier_manufacturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premierproduct',
            name='manufacturer',
        ),
    ]
