# Generated by Django 2.2.5 on 2019-10-22 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0053_remove_premierproduct_manufacturer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='premierproduct',
            old_name='manufacturer2',
            new_name='manufacturer',
        ),
    ]
