# Generated by Django 2.2.5 on 2019-10-22 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0055_premier_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premierproduct',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.PremierManufacturer'),
        ),
    ]
