# Generated by Django 2.2.5 on 2019-10-22 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0056_premier_manufacturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premier_manufacturer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.PremierManufacturer')),
                ('sema_brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.SemaBrand', verbose_name='SEMA brand')),
            ],
            bases=(models.Model,),
        ),
    ]
