# Generated by Django 2.2.5 on 2019-10-22 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0057_vendor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manufacturer',
        ),
    ]
