# Generated by Django 2.2.5 on 2019-10-22 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0059_product_semaproduct'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AlterModelTable(
                    'premiermanufacturer', 'premier_premiermanufacturer'
                ),
                migrations.AlterModelTable(
                    'premierproduct', 'premier_premierproduct'
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='premierproduct',
                    name='manufacturer',
                ),
                migrations.AlterField(
                    model_name='product',
                    name='premier_product',
                    field=models.OneToOneField(blank=True, null=True,
                                               on_delete=django.db.models.deletion.SET_NULL,
                                               related_name='product',
                                               to='premier.PremierProduct'),
                ),
                migrations.AlterField(
                    model_name='vendor',
                    name='premier_manufacturer',
                    field=models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='premier.PremierManufacturer'),
                ),
                migrations.DeleteModel(
                    name='PremierManufacturer',
                ),
                migrations.DeleteModel(
                    name='PremierProduct',
                ),
            ]
        ),
    ]
