# Generated by Django 2.2.5 on 2019-10-22 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0060_auto_20191022_2309'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AlterModelTable(
                    'semabrand', 'sema_semabrand'
                ),
                migrations.AlterModelTable(
                    'semadataset', 'sema_semadataset'
                ),
                migrations.AlterModelTable(
                    'semayear', 'sema_semayear'
                ),
                migrations.AlterModelTable(
                    'semamake', 'sema_semamake'
                ),
                migrations.AlterModelTable(
                    'semamodel', 'sema_semamodel'
                ),
                migrations.AlterModelTable(
                    'semasubmodel', 'sema_semasubmodel'
                ),
                migrations.AlterModelTable(
                    'semamakeyear', 'sema_semamakeyear'
                ),
                migrations.AlterModelTable(
                    'semabasevehicle', 'sema_semabasevehicle'
                ),
                migrations.AlterModelTable(
                    'semavehicle', 'sema_semavehicle'
                ),
                migrations.AlterModelTable(
                    'semacategory', 'sema_semacategory'
                ),
                migrations.AlterModelTable(
                    'semaproduct', 'sema_semaproduct'
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='semacategory',
                    name='parent_categories',
                ),
                migrations.RemoveField(
                    model_name='semadataset',
                    name='brand',
                ),
                migrations.AlterUniqueTogether(
                    name='semamakeyear',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='semamakeyear',
                    name='make',
                ),
                migrations.RemoveField(
                    model_name='semamakeyear',
                    name='year',
                ),
                migrations.RemoveField(
                    model_name='semaproduct',
                    name='categories',
                ),
                migrations.RemoveField(
                    model_name='semaproduct',
                    name='dataset',
                ),
                migrations.RemoveField(
                    model_name='semaproduct',
                    name='vehicles',
                ),
                migrations.RemoveField(
                    model_name='semavehicle',
                    name='base_vehicle',
                ),
                migrations.RemoveField(
                    model_name='semavehicle',
                    name='submodel',
                ),
                migrations.AlterField(
                    model_name='product',
                    name='sema_product',
                    field=models.ForeignKey(blank=True, null=True,
                                            on_delete=django.db.models.deletion.SET_NULL,
                                            related_name='products',
                                            to='sema.SemaProduct',
                                            verbose_name='SEMA product'),
                ),
                migrations.AlterField(
                    model_name='vendor',
                    name='sema_brand',
                    field=models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='sema.SemaBrand', verbose_name='SEMA brand'),
                ),
                migrations.DeleteModel(
                    name='SemaBaseVehicle',
                ),
                migrations.DeleteModel(
                    name='SemaBrand',
                ),
                migrations.DeleteModel(
                    name='SemaCategory',
                ),
                migrations.DeleteModel(
                    name='SemaDataset',
                ),
                migrations.DeleteModel(
                    name='SemaMake',
                ),
                migrations.DeleteModel(
                    name='SemaMakeYear',
                ),
                migrations.DeleteModel(
                    name='SemaModel',
                ),
                migrations.DeleteModel(
                    name='SemaProduct',
                ),
                migrations.DeleteModel(
                    name='SemaSubmodel',
                ),
                migrations.DeleteModel(
                    name='SemaVehicle',
                ),
                migrations.DeleteModel(
                    name='SemaYear',
                ),
            ]
        ),
    ]
