# Generated by Django 2.2.5 on 2019-10-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semaproduct',
            name='part_number',
            field=models.CharField(max_length=30),
        ),
    ]
