# Generated by Django 2.2.5 on 2019-10-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sema', '0002_semaproduct_part_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semacategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
