# Generated by Django 2.2.5 on 2019-10-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sema', '0003_semacategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='semabrand',
            name='is_relevant',
            field=models.BooleanField(default=False),
        ),
    ]
