# Generated by Django 2.2.5 on 2019-10-27 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sema', '0013_semaproduct_is_relevant'),
    ]

    operations = [
        migrations.AddField(
            model_name='semabrand',
            name='primary_image_url',
            field=models.URLField(blank=True),
        ),
    ]
