# Generated by Django 2.2.5 on 2019-10-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sema', '0014_semabrand_primary_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='semaproduct',
            name='pies_c10_tle',
            field=models.CharField(blank=True, max_length=100, verbose_name='title'),
        ),
    ]
