# Generated by Django 2.2.5 on 2019-10-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sema', '0015_semaproduct_pies_c10_tle'),
    ]

    operations = [
        migrations.AddField(
            model_name='semaproduct',
            name='pies_c10_ext',
            field=models.CharField(blank=True, max_length=200, verbose_name='description'),
        ),
    ]
