# Generated by Django 2.2.5 on 2019-10-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sema', '0017_semaproduct_pies_c10_des'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semaproduct',
            name='pies_c10_ext',
            field=models.CharField(blank=True, max_length=500, verbose_name='description'),
        ),
    ]
