# Generated by Django 2.2.5 on 2019-10-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sema', '0027_semabasevehicle_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='semavehicle',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
