# Generated by Django 2.2.5 on 2019-10-28 05:47

import core.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sema', '0030_semaproduct_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemaDescriptionPiesAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_relevant', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('is_authorized', models.BooleanField(default=False, help_text='brand has given access to dataset')),
                ('segment', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=500)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sema.SemaProduct')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, core.mixins.MessagesMixin),
        ),
    ]
