# Generated by Django 2.2.5 on 2019-10-28 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sema', '0035_semaproduct_pies_c10_ext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semaproduct',
            name='primary_image_url',
        ),
    ]
