# Generated by Django 2.2.5 on 2019-10-28 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sema', '0036_semaproduct_primary_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semadescriptionpiesattribute',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description_pies_attributes', to='sema.SemaProduct'),
        ),
    ]
