# Generated by Django 2.2.5 on 2019-10-28 07:44

import core.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sema', '0037_semadescriptionpiesattribute_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemaDigitalAssetsPiesAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_relevant', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('is_authorized', models.BooleanField(default=False, help_text='brand has given access to dataset')),
                ('segment', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=500)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_assets_pies_attributes', to='sema.SemaProduct')),
            ],
            options={
                'verbose_name': 'SEMA description PIES',
            },
            bases=(models.Model, core.mixins.MessagesMixin),
        ),
    ]
