# Generated by Django 2.2.5 on 2019-10-28 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sema', '0038_semadigitalassetspiesattribute'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semadescriptionpiesattribute',
            options={'verbose_name': 'SEMA description PIES', 'verbose_name_plural': 'SEMA description PIES'},
        ),
        migrations.AlterModelOptions(
            name='semadigitalassetspiesattribute',
            options={'verbose_name': 'SEMA digital assets PIES', 'verbose_name_plural': 'SEMA digital assets PIES'},
        ),
    ]
