# Generated by Django 2.2.5 on 2019-10-31 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sema', '0039_semapiesattribute_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semadigitalassetspiesattribute',
            name='value',
            field=models.URLField(max_length=500),
        ),
    ]
