# Generated by Django 2.2.5 on 2019-11-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sema', '0041_semadataset_vehicles'),
    ]

    operations = [
        migrations.AddField(
            model_name='semadataset',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='datasets', to='sema.SemaCategory'),
        ),
    ]
