# Generated by Django 2.2.5 on 2019-11-01 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sema', '0042_semadataset_categories'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='semabasevehicle',
            unique_together={('make_year', 'model')},
        ),
        migrations.AlterUniqueTogether(
            name='semaproduct',
            unique_together={('dataset', 'part_number')},
        ),
        migrations.AlterUniqueTogether(
            name='semavehicle',
            unique_together={('base_vehicle', 'submodel')},
        ),
    ]
