# Generated by Django 2.2.5 on 2019-11-05 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sema', '0043_sema_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semadescriptionpiesattribute',
            name='is_authorized',
        ),
        migrations.RemoveField(
            model_name='semadescriptionpiesattribute',
            name='is_relevant',
        ),
        migrations.RemoveField(
            model_name='semadescriptionpiesattribute',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='semadigitalassetspiesattribute',
            name='is_authorized',
        ),
        migrations.RemoveField(
            model_name='semadigitalassetspiesattribute',
            name='is_relevant',
        ),
        migrations.RemoveField(
            model_name='semadigitalassetspiesattribute',
            name='notes',
        ),
    ]
