# Generated by Django 2.2.5 on 2019-11-08 18:11

import core.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sema', '0044_sema_pies_relevance'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemaEngine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_relevant', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('is_authorized', models.BooleanField(default=False, help_text='brand has given access to dataset')),
                ('litre', models.CharField(max_length=10)),
                ('cc', models.CharField(max_length=10)),
                ('cid', models.CharField(max_length=10)),
                ('cylinders', models.CharField(max_length=10)),
                ('block_type', models.CharField(max_length=10)),
                ('engine_bore_in', models.CharField(max_length=10)),
                ('engine_bore_metric', models.CharField(max_length=10)),
                ('engine_stroke_in', models.CharField(max_length=10)),
                ('engine_stroke_metric', models.CharField(max_length=10)),
                ('valves_per_engine', models.CharField(max_length=10)),
                ('aspiration', models.CharField(max_length=10)),
                ('cylinder_head_type', models.CharField(max_length=10)),
                ('fuel_type', models.CharField(max_length=10)),
                ('ignition_system_type', models.CharField(max_length=10)),
                ('manufacturer', models.CharField(max_length=10)),
                ('horse_power', models.CharField(max_length=10)),
                ('kilowatt_power', models.CharField(max_length=10)),
                ('engine_designation', models.CharField(max_length=10)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engines', to='sema.SemaVehicle')),
            ],
            options={
                'verbose_name': 'SEMA engine',
            },
            bases=(models.Model, core.mixins.MessagesMixin),
        ),
    ]
