# Generated by Django 2.2.5 on 2019-11-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sema', '0046_semaengine_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semaengine',
            name='fuel_type',
            field=models.CharField(max_length=20),
        ),
    ]
