# Generated by Django 2.2.5 on 2019-11-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sema', '0047_semaengine_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semaengine',
            name='manufacturer',
            field=models.CharField(max_length=50),
        ),
    ]
