# Generated by Django 2.2.5 on 2019-12-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sema', '0049_relevancy_and_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semadescriptionpiesattribute',
            name='value',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='semadigitalassetspiesattribute',
            name='value',
            field=models.URLField(max_length=100),
        ),
    ]
