# Generated by Django 2.2.5 on 2019-12-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sema', '0050_sema_pies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semadescriptionpiesattribute',
            name='value',
            field=models.CharField(max_length=2000),
        ),
    ]
