# Generated by Django 2.2.5 on 2019-12-05 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sema', '0052_sema_pies'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='semaengine',
            unique_together={('vehicle', 'litre', 'cc', 'cid', 'cylinders', 'block_type', 'engine_bore_in', 'engine_bore_metric', 'engine_stroke_in', 'engine_stroke_metric', 'valves_per_engine', 'aspiration', 'cylinder_head_type', 'fuel_type', 'ignition_system_type', 'manufacturer', 'horse_power', 'kilowatt_power', 'engine_designation')},
        ),
    ]
