# Generated by Django 2.2.5 on 2019-12-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sema', '0053_semaengine'),
    ]

    operations = [
        migrations.AddField(
            model_name='semabasevehicle',
            name='relevancy_exception',
            field=models.CharField(blank=True, max_length=255, verbose_name='exception'),
        ),
        migrations.AddField(
            model_name='semabrand',
            name='relevancy_exception',
            field=models.CharField(blank=True, max_length=255, verbose_name='exception'),
        ),
        migrations.AddField(
            model_name='semacategory',
            name='relevancy_exception',
            field=models.CharField(blank=True, max_length=255, verbose_name='exception'),
        ),
        migrations.AddField(
            model_name='semadataset',
            name='relevancy_exception',
            field=models.CharField(blank=True, max_length=255, verbose_name='exception'),
        ),
        migrations.AddField(
            model_name='semaengine',
            name='relevancy_exception',
            field=models.CharField(blank=True, max_length=255, verbose_name='exception'),
        ),
        migrations.AddField(
            model_name='semamake',
            name='relevancy_exception',
            field=models.CharField(blank=True, max_length=255, verbose_name='exception'),
        ),
        migrations.AddField(
            model_name='semamakeyear',
            name='relevancy_exception',
            field=models.CharField(blank=True, max_length=255, verbose_name='exception'),
        ),
        migrations.AddField(
            model_name='semamodel',
            name='relevancy_exception',
            field=models.CharField(blank=True, max_length=255, verbose_name='exception'),
        ),
        migrations.AddField(
            model_name='semaproduct',
            name='relevancy_exception',
            field=models.CharField(blank=True, max_length=255, verbose_name='exception'),
        ),
        migrations.AddField(
            model_name='semasubmodel',
            name='relevancy_exception',
            field=models.CharField(blank=True, max_length=255, verbose_name='exception'),
        ),
        migrations.AddField(
            model_name='semavehicle',
            name='relevancy_exception',
            field=models.CharField(blank=True, max_length=255, verbose_name='exception'),
        ),
        migrations.AddField(
            model_name='semayear',
            name='relevancy_exception',
            field=models.CharField(blank=True, max_length=255, verbose_name='exception'),
        ),
    ]
